# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iconsdeneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(447, 457)
        MainWindow.setMinimumSize(QtCore.QSize(447, 457))
        MainWindow.setMaximumSize(QtCore.QSize(447, 457))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(447, 457))
        self.centralwidget.setMaximumSize(QtCore.QSize(447, 457))
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-image: url(:/icons/icons.jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.kullanicilabel = QtWidgets.QLabel(self.centralwidget)
        self.kullanicilabel.setObjectName("kullanicilabel")
        self.gridLayout.addWidget(self.kullanicilabel, 2, 1, 1, 1)
        self.kullanicigiris = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanicigiris.setObjectName("kullanicigiris")
        self.gridLayout.addWidget(self.kullanicigiris, 2, 2, 1, 2)
        self.parolagiris = QtWidgets.QLineEdit(self.centralwidget)
        self.parolagiris.setObjectName("parolagiris")
        self.gridLayout.addWidget(self.parolagiris, 3, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.girisbuton = QtWidgets.QPushButton(self.centralwidget)
        self.girisbuton.setObjectName("girisbuton")
        self.gridLayout.addWidget(self.girisbuton, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.parolalabel = QtWidgets.QLabel(self.centralwidget)
        self.parolalabel.setObjectName("parolalabel")
        self.gridLayout.addWidget(self.parolalabel, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.kaydolbuton = QtWidgets.QPushButton(self.centralwidget)
        self.kaydolbuton.setObjectName("kaydolbuton")
        self.gridLayout.addWidget(self.kaydolbuton, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.bilgilabel = QtWidgets.QLabel(self.centralwidget)
        self.bilgilabel.setMaximumSize(QtCore.QSize(200, 20))
        self.bilgilabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bilgilabel.setObjectName("bilgilabel")
        self.gridLayout.addWidget(self.bilgilabel, 1, 2, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kullanicilabel.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.girisbuton.setText(_translate("MainWindow", "Giriş Yap"))
        self.parolalabel.setText(_translate("MainWindow", "Parola:"))
        self.kaydolbuton.setText(_translate("MainWindow", "Kayıt Ol"))
        self.bilgilabel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
