# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayıtekranı.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 398)
        Form.setMinimumSize(QtCore.QSize(369, 338))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setStyleSheet("#Form{\n"
"    background-image: url(:/icons/icons.jpg);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.isimlabel = QtWidgets.QLabel(Form)
        self.isimlabel.setObjectName("isimlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.isimlabel)
        self.soyisimlabel = QtWidgets.QLabel(Form)
        self.soyisimlabel.setObjectName("soyisimlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.soyisimlabel)
        self.kullanicilabel = QtWidgets.QLabel(Form)
        self.kullanicilabel.setObjectName("kullanicilabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.kullanicilabel)
        self.parolalabel = QtWidgets.QLabel(Form)
        self.parolalabel.setObjectName("parolalabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.parolalabel)
        self.kayitol = QtWidgets.QPushButton(Form)
        self.kayitol.setObjectName("kayitol")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.kayitol)
        self.isim = QtWidgets.QLineEdit(Form)
        self.isim.setObjectName("isim")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isim)
        self.soyisim = QtWidgets.QLineEdit(Form)
        self.soyisim.setObjectName("soyisim")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soyisim)
        self.kullaniciadi = QtWidgets.QLineEdit(Form)
        self.kullaniciadi.setObjectName("kullaniciadi")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.kullaniciadi)
        self.parola = QtWidgets.QLineEdit(Form)
        self.parola.setObjectName("parola")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.parola)
        self.tellabel = QtWidgets.QLabel(Form)
        self.tellabel.setObjectName("tellabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tellabel)
        self.tarihlabel = QtWidgets.QLabel(Form)
        self.tarihlabel.setObjectName("tarihlabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tarihlabel)
        self.boylabel = QtWidgets.QLabel(Form)
        self.boylabel.setObjectName("boylabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.boylabel)
        self.kilolabel = QtWidgets.QLabel(Form)
        self.kilolabel.setObjectName("kilolabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.kilolabel)
        self.telefon = QtWidgets.QLineEdit(Form)
        self.telefon.setObjectName("telefon")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.telefon)
        self.dogumtarih = QtWidgets.QLineEdit(Form)
        self.dogumtarih.setObjectName("dogumtarih")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dogumtarih)
        self.boy = QtWidgets.QLineEdit(Form)
        self.boy.setObjectName("boy")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.boy)
        self.kilo = QtWidgets.QLineEdit(Form)
        self.kilo.setObjectName("kilo")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.kilo)
        self.gridLayout.addLayout(self.formLayout, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.bilgilabel = QtWidgets.QLabel(Form)
        self.bilgilabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bilgilabel.setText("")
        self.bilgilabel.setObjectName("bilgilabel")
        self.gridLayout.addWidget(self.bilgilabel, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.isimlabel.setText(_translate("Form", "İsim:"))
        self.soyisimlabel.setText(_translate("Form", "Soyisim:"))
        self.kullanicilabel.setText(_translate("Form", "Kullanıcı Adı:"))
        self.parolalabel.setText(_translate("Form", "Parola:"))
        self.kayitol.setText(_translate("Form", "Kayıt Ol"))
        self.tellabel.setText(_translate("Form", "Telefon Numarası:"))
        self.tarihlabel.setText(_translate("Form", "Doğum Tarihi:"))
        self.boylabel.setText(_translate("Form", "Boy:"))
        self.kilolabel.setText(_translate("Form", "Kilo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
